# Generated by Django 3.0 on 2020-01-11 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='is_master',
        ),
    ]
